server:
  port: 8891
spring:
  application:
    name: ace-syslog

  kafka:
    bootstrap-servers: 192.168.5.101:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  http:
    encoding:
      charset: UTF-8
      force-response: true
      force-request: true
logging:
  file: logs/${spring.application.name}.log
  level:
    root: info
app:
  su:
    # 启用es与kafka发送数据，启用为true，不启用为 false
    es: false
    kafka: true