spring:
  redis:
    # 数据库地址
    database: 8
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        # 连接池最大连接数(使用负值表示没有限制)
        max-active: -1
        # 连接池中的最大空闲连接
        max-idle: 50
        # 连接池中的最小空闲连接
        min-idle: 20
        # 连接池最大阻塞等待时间(使用负值表示没有限制)
        max-wait: -1
    password:
    # 连接超时时间(毫秒)
    timeout: 10000
    #控制一个pool可分配多少个jedis实例,用来替换上面的redis.maxActive,如果是jedis 2.4以后用该属性
    pool:
      max-total: 1000
      # 连接池最大连接数(使用负值表示没有限制)
    lettuce:
      pool:
        max-active: 10